# Generated by Django 2.1.7 on 2019-03-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', models.IntegerField(choices=[('Python', 0), ('C/C++', 1)])),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='people.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('Waiting', 0), ('Running', 1), ('OK', 2), ('WA', 3), ('Compilation error', 4), ('Segmentation fault', 5), ('Runtime exception', 6)])),
                ('log_file', models.FileField(upload_to='scoring_logs')),
                ('scoring_task_id', models.CharField(max_length=36, null=True)),
                ('submit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submit.Submit')),
            ],
        ),
    ]
