# Generated by Django 2.1.7 on 2019-03-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submits')),
                ('language', models.IntegerField(choices=[('Python', 0), ('C/C++', 1)])),
                ('scoring_task_id', models.CharField(max_length=36, null=True)),
                ('status', models.IntegerField(choices=[('Waiting', 0), ('Running', 1), ('OK', 2), ('WA', 3), ('Compilation error', 4), ('Segmentation fault', 5), ('Runtime exception', 6)], default=0)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(upload_to='scoring_logs')),
                ('points', models.IntegerField(default=0)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submit.Submit')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('assignment_text', models.TextField()),
                ('input_path', models.TextField()),
                ('max_points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submits', to='submit.Task'),
        ),
    ]
