# Generated by Django 2.2 on 2019-04-27 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submits')),
                ('language', models.IntegerField(choices=[(0, 'Python'), (1, 'C/C++')])),
                ('scoring_task_id', models.CharField(blank=True, max_length=36, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'OK'), (3, 'WA'), (4, 'Compilation error'), (5, 'Runtime exception'), (6, 'Time limit exceeded')], default=0)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignment', models.FileField(null=True, upload_to='tasks')),
                ('max_points', models.IntegerField()),
                ('time_limit', models.IntegerField(default=5000)),
                ('memory_limit', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compilation_message', models.TextField(default='')),
                ('log_file', models.FileField(upload_to='scoring_logs')),
                ('points', models.IntegerField(default=0)),
                ('date_scored', models.DateTimeField(auto_now_add=True, null=True)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submit.Submit')),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submits', to='submit.Task'),
        ),
    ]
