# Generated by Django 2.1.7 on 2019-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignment_text',
        ),
        migrations.AddField(
            model_name='task',
            name='assignment',
            field=models.FileField(null=True, upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
