# Generated by Django 2.1.7 on 2019-03-27 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20190318_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitscore',
            name='date_scored',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submit',
            name='language',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'C/C++')]),
        ),
        migrations.AlterField(
            model_name='submit',
            name='scoring_task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'OK'), (3, 'WA'), (4, 'Compilation error'), (5, 'Segmentation fault'), (6, 'Runtime exception')], default=0),
        ),
    ]
