# Generated by Django 2.1.7 on 2019-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20190327_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='input_path',
        ),
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'OK'), (3, 'WA'), (4, 'Compilation error'), (5, 'Runtime exception'), (6, 'Time limit exceeded')], default=0),
        ),
    ]
