# Generated by Django 2.1.7 on 2019-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20190327_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
