# Generated by Django 2.1.7 on 2019-03-27 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190318_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logged_in',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
