# Generated by Django 2.1.7 on 2019-03-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_team_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetoothtag',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='people.Team'),
        ),
    ]
