# Generated by Django 2.1.7 on 2019-04-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190406_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinesupply',
            name='participant',
        ),
        migrations.AddField(
            model_name='medicinesupply',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_supplies', to='people.Team'),
            preserve_default=False,
        ),
    ]
