# Generated by Django 2.2 on 2019-04-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Infectious'), (1, 'Degenerative')])),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_duration', models.IntegerField(default=5)),
                ('cooldown_duration', models.IntegerField(default=60)),
                ('severity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=5)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_multiplier', models.FloatField(default=0.5)),
                ('effect_multiplier', models.FloatField(default=0.5)),
                ('cooldown_multiplier', models.FloatField(default=2)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_medicines', to='pandemic.DiseaseClass')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pandemic.MedicineClass')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseTransmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='pandemic.DiseaseClass')),
            ],
        ),
    ]
