# Generated by Django 2.1.7 on 2019-03-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[('Infectious', 0), ('Degenerative', 1)])),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseTransmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='pandemic.DiseaseClass')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_medicines', to='pandemic.DiseaseClass')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pandemic.MedicineClass')),
            ],
        ),
    ]
