# Generated by Django 2.2 on 2019-04-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('pandemic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasetransmit',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='people.BluetoothTag'),
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pandemic.DiseaseClass'),
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='people.Team'),
        ),
    ]
