# Generated by Django 2.1.7 on 2019-03-27 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pandemic', '0002_diseasetransmit_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='diseaseclass',
            name='type',
            field=models.IntegerField(choices=[(0, 'Infectious'), (1, 'Degenerative')]),
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pandemic.DiseaseClass'),
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to=settings.AUTH_USER_MODEL),
        ),
    ]
