# Generated by Django 2.2 on 2019-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('pandemic', '0002_auto_20190427_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseclass',
            name='type',
        ),
        migrations.AlterField(
            model_name='diseaseclass',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='medicineclass',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='diseaseinstance',
            unique_together={('disease', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='diseasetransmit',
            unique_together={('disease', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='medicineeffect',
            unique_together={('medicine', 'disease')},
        ),
    ]
