# Generated by Django 2.1.7 on 2019-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0003_auto_20190327_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseinstance',
            name='cooldown_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='effect_duration',
            field=models.IntegerField(default=5),
        ),
    ]
