# Generated by Django 2.1.7 on 2019-04-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190328_1159'),
        ('pandemic', '0004_auto_20190406_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseinstance',
            name='participant',
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='people.Team'),
            preserve_default=False,
        ),
    ]
