# Generated by Django 2.1.7 on 2019-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0005_auto_20190406_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineeffect',
            name='strength',
        ),
        migrations.AddField(
            model_name='medicineclass',
            name='price',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='medicineeffect',
            name='cooldown_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicineeffect',
            name='effect_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicineeffect',
            name='severity_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
