# Generated by Django 2.1.7 on 2019-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0006_auto_20190406_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineeffect',
            name='cooldown_multiplier',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='medicineeffect',
            name='effect_multiplier',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='medicineeffect',
            name='severity_multiplier',
            field=models.FloatField(default=0.5),
        ),
    ]
